import { prisma } from "../../config/prisma-config";

async function main() {
  console.log("🌱 Inizio seeding Country & Language...");

  // Svuota solo la tabella Country (mantiene Language esistenti)
  console.log("🗑️  Svuotamento tabella Country...");
  await prisma.country.deleteMany({});
  console.log("✅ Tabella Country svuotata");

  // Seed Countries
  console.log("🌍 Creazione paesi...");

  const countriesData = [
    // Paesi EU (27 membri attuali)
    {
      code: "AT",
      iso3: "AUT",
      numericCode: "040",
      phoneCode: "+43",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Austria",
      isEU: true,
      languages: ["de"],
    },
    {
      code: "BE",
      iso3: "BEL",
      numericCode: "056",
      phoneCode: "+32",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Belgio",
      isEU: true,
      languages: ["nl", "fr", "de"],
    },
    {
      code: "BG",
      iso3: "BGR",
      numericCode: "100",
      phoneCode: "+359",
      continent: "Europe",
      currencyCode: "BGN",
      name: "Bulgaria",
      isEU: true,
      languages: [],
    },
    {
      code: "HR",
      iso3: "HRV",
      numericCode: "191",
      phoneCode: "+385",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Croazia",
      isEU: true,
      languages: [],
    },
    {
      code: "CY",
      iso3: "CYP",
      numericCode: "196",
      phoneCode: "+357",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Cipro",
      isEU: true,
      languages: [],
    },
    {
      code: "CZ",
      iso3: "CZE",
      numericCode: "203",
      phoneCode: "+420",
      continent: "Europe",
      currencyCode: "CZK",
      name: "Repubblica Ceca",
      isEU: true,
      languages: [],
    },
    {
      code: "DK",
      iso3: "DNK",
      numericCode: "208",
      phoneCode: "+45",
      continent: "Europe",
      currencyCode: "DKK",
      name: "Danimarca",
      isEU: true,
      languages: [],
    },
    {
      code: "EE",
      iso3: "EST",
      numericCode: "233",
      phoneCode: "+372",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Estonia",
      isEU: true,
      languages: [],
    },
    {
      code: "FI",
      iso3: "FIN",
      numericCode: "246",
      phoneCode: "+358",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Finlandia",
      isEU: true,
      languages: [],
    },
    {
      code: "FR",
      iso3: "FRA",
      numericCode: "250",
      phoneCode: "+33",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Francia",
      isEU: true,
      languages: ["fr"],
    },
    {
      code: "DE",
      iso3: "DEU",
      numericCode: "276",
      phoneCode: "+49",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Germania",
      isEU: true,
      languages: ["de"],
    },
    {
      code: "GR",
      iso3: "GRC",
      numericCode: "300",
      phoneCode: "+30",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Grecia",
      isEU: true,
      languages: [],
    },
    {
      code: "HU",
      iso3: "HUN",
      numericCode: "348",
      phoneCode: "+36",
      continent: "Europe",
      currencyCode: "HUF",
      name: "Ungheria",
      isEU: true,
      languages: [],
    },
    {
      code: "IE",
      iso3: "IRL",
      numericCode: "372",
      phoneCode: "+353",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Irlanda",
      isEU: true,
      languages: ["en"],
    },
    {
      code: "IT",
      iso3: "ITA",
      numericCode: "380",
      phoneCode: "+39",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Italia",
      isEU: true,
      languages: ["it"],
    },
    {
      code: "LV",
      iso3: "LVA",
      numericCode: "428",
      phoneCode: "+371",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Lettonia",
      isEU: true,
      languages: [],
    },
    {
      code: "LT",
      iso3: "LTU",
      numericCode: "440",
      phoneCode: "+370",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Lituania",
      isEU: true,
      languages: [],
    },
    {
      code: "LU",
      iso3: "LUX",
      numericCode: "442",
      phoneCode: "+352",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Lussemburgo",
      isEU: true,
      languages: ["fr", "de"],
    },
    {
      code: "MT",
      iso3: "MLT",
      numericCode: "470",
      phoneCode: "+356",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Malta",
      isEU: true,
      languages: ["en"],
    },
    {
      code: "NL",
      iso3: "NLD",
      numericCode: "528",
      phoneCode: "+31",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Paesi Bassi",
      isEU: true,
      languages: [],
    },
    {
      code: "PL",
      iso3: "POL",
      numericCode: "616",
      phoneCode: "+48",
      continent: "Europe",
      currencyCode: "PLN",
      name: "Polonia",
      isEU: true,
      languages: [],
    },
    {
      code: "PT",
      iso3: "PRT",
      numericCode: "620",
      phoneCode: "+351",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Portogallo",
      isEU: true,
      languages: [],
    },
    {
      code: "RO",
      iso3: "ROU",
      numericCode: "642",
      phoneCode: "+40",
      continent: "Europe",
      currencyCode: "RON",
      name: "Romania",
      isEU: true,
      languages: [],
    },
    {
      code: "SK",
      iso3: "SVK",
      numericCode: "703",
      phoneCode: "+421",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Slovacchia",
      isEU: true,
      languages: [],
    },
    {
      code: "SI",
      iso3: "SVN",
      numericCode: "705",
      phoneCode: "+386",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Slovenia",
      isEU: true,
      languages: [],
    },
    {
      code: "ES",
      iso3: "ESP",
      numericCode: "724",
      phoneCode: "+34",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Spagna",
      isEU: true,
      languages: ["es"],
    },
    {
      code: "SE",
      iso3: "SWE",
      numericCode: "752",
      phoneCode: "+46",
      continent: "Europe",
      currencyCode: "SEK",
      name: "Svezia",
      isEU: true,
      languages: [],
    },

    // Altri paesi europei (non-EU)
    {
      code: "GB",
      iso3: "GBR",
      numericCode: "826",
      phoneCode: "+44",
      continent: "Europe",
      currencyCode: "GBP",
      name: "Regno Unito",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "CH",
      iso3: "CHE",
      numericCode: "756",
      phoneCode: "+41",
      continent: "Europe",
      currencyCode: "CHF",
      name: "Svizzera",
      isEU: false,
      languages: ["de", "fr", "it"],
    },
    {
      code: "NO",
      iso3: "NOR",
      numericCode: "578",
      phoneCode: "+47",
      continent: "Europe",
      currencyCode: "NOK",
      name: "Norvegia",
      isEU: false,
      languages: [],
    },
    {
      code: "IS",
      iso3: "ISL",
      numericCode: "352",
      phoneCode: "+354",
      continent: "Europe",
      currencyCode: "ISK",
      name: "Islanda",
      isEU: false,
      languages: [],
    },
    {
      code: "RS",
      iso3: "SRB",
      numericCode: "688",
      phoneCode: "+381",
      continent: "Europe",
      currencyCode: "RSD",
      name: "Serbia",
      isEU: false,
      languages: [],
    },
    {
      code: "UA",
      iso3: "UKR",
      numericCode: "804",
      phoneCode: "+380",
      continent: "Europe",
      currencyCode: "UAH",
      name: "Ucraina",
      isEU: false,
      languages: [],
    },
    {
      code: "TR",
      iso3: "TUR",
      numericCode: "792",
      phoneCode: "+90",
      continent: "Asia",
      currencyCode: "TRY",
      name: "Turchia",
      isEU: false,
      languages: [],
    },
    {
      code: "AL",
      iso3: "ALB",
      numericCode: "008",
      phoneCode: "+355",
      continent: "Europe",
      currencyCode: "ALL",
      name: "Albania",
      isEU: false,
      languages: [],
    },
    {
      code: "BA",
      iso3: "BIH",
      numericCode: "070",
      phoneCode: "+387",
      continent: "Europe",
      currencyCode: "BAM",
      name: "Bosnia ed Erzegovina",
      isEU: false,
      languages: [],
    },
    {
      code: "MK",
      iso3: "MKD",
      numericCode: "807",
      phoneCode: "+389",
      continent: "Europe",
      currencyCode: "MKD",
      name: "Macedonia del Nord",
      isEU: false,
      languages: [],
    },
    {
      code: "ME",
      iso3: "MNE",
      numericCode: "499",
      phoneCode: "+382",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Montenegro",
      isEU: false,
      languages: [],
    },
    {
      code: "XK",
      iso3: "XKX",
      numericCode: "383",
      phoneCode: "+383",
      continent: "Europe",
      currencyCode: "EUR",
      name: "Kosovo",
      isEU: false,
      languages: [],
    },
    {
      code: "BY",
      iso3: "BLR",
      numericCode: "112",
      phoneCode: "+375",
      continent: "Europe",
      currencyCode: "BYN",
      name: "Bielorussia",
      isEU: false,
      languages: [],
    },
    {
      code: "MD",
      iso3: "MDA",
      numericCode: "498",
      phoneCode: "+373",
      continent: "Europe",
      currencyCode: "MDL",
      name: "Moldavia",
      isEU: false,
      languages: [],
    },
    {
      code: "RU",
      iso3: "RUS",
      numericCode: "643",
      phoneCode: "+7",
      continent: "Europe",
      currencyCode: "RUB",
      name: "Russia",
      isEU: false,
      languages: [],
    },

    // Principali paesi mondiali
    {
      code: "US",
      iso3: "USA",
      numericCode: "840",
      phoneCode: "+1",
      continent: "North America",
      currencyCode: "USD",
      name: "Stati Uniti",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "CA",
      iso3: "CAN",
      numericCode: "124",
      phoneCode: "+1",
      continent: "North America",
      currencyCode: "CAD",
      name: "Canada",
      isEU: false,
      languages: ["en", "fr"],
    },
    {
      code: "MX",
      iso3: "MEX",
      numericCode: "484",
      phoneCode: "+52",
      continent: "North America",
      currencyCode: "MXN",
      name: "Messico",
      isEU: false,
      languages: ["es"],
    },
    {
      code: "BR",
      iso3: "BRA",
      numericCode: "076",
      phoneCode: "+55",
      continent: "South America",
      currencyCode: "BRL",
      name: "Brasile",
      isEU: false,
      languages: [],
    },
    {
      code: "AR",
      iso3: "ARG",
      numericCode: "032",
      phoneCode: "+54",
      continent: "South America",
      currencyCode: "ARS",
      name: "Argentina",
      isEU: false,
      languages: ["es"],
    },
    {
      code: "CN",
      iso3: "CHN",
      numericCode: "156",
      phoneCode: "+86",
      continent: "Asia",
      currencyCode: "CNY",
      name: "Cina",
      isEU: false,
      languages: [],
    },
    {
      code: "JP",
      iso3: "JPN",
      numericCode: "392",
      phoneCode: "+81",
      continent: "Asia",
      currencyCode: "JPY",
      name: "Giappone",
      isEU: false,
      languages: [],
    },
    {
      code: "KR",
      iso3: "KOR",
      numericCode: "410",
      phoneCode: "+82",
      continent: "Asia",
      currencyCode: "KRW",
      name: "Corea del Sud",
      isEU: false,
      languages: [],
    },
    {
      code: "IN",
      iso3: "IND",
      numericCode: "356",
      phoneCode: "+91",
      continent: "Asia",
      currencyCode: "INR",
      name: "India",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "AU",
      iso3: "AUS",
      numericCode: "036",
      phoneCode: "+61",
      continent: "Oceania",
      currencyCode: "AUD",
      name: "Australia",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "NZ",
      iso3: "NZL",
      numericCode: "554",
      phoneCode: "+64",
      continent: "Oceania",
      currencyCode: "NZD",
      name: "Nuova Zelanda",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "ZA",
      iso3: "ZAF",
      numericCode: "710",
      phoneCode: "+27",
      continent: "Africa",
      currencyCode: "ZAR",
      name: "Sudafrica",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "EG",
      iso3: "EGY",
      numericCode: "818",
      phoneCode: "+20",
      continent: "Africa",
      currencyCode: "EGP",
      name: "Egitto",
      isEU: false,
      languages: [],
    },
    {
      code: "SA",
      iso3: "SAU",
      numericCode: "682",
      phoneCode: "+966",
      continent: "Asia",
      currencyCode: "SAR",
      name: "Arabia Saudita",
      isEU: false,
      languages: [],
    },
    {
      code: "AE",
      iso3: "ARE",
      numericCode: "784",
      phoneCode: "+971",
      continent: "Asia",
      currencyCode: "AED",
      name: "Emirati Arabi Uniti",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "SG",
      iso3: "SGP",
      numericCode: "702",
      phoneCode: "+65",
      continent: "Asia",
      currencyCode: "SGD",
      name: "Singapore",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "TH",
      iso3: "THA",
      numericCode: "764",
      phoneCode: "+66",
      continent: "Asia",
      currencyCode: "THB",
      name: "Thailandia",
      isEU: false,
      languages: [],
    },
    {
      code: "ID",
      iso3: "IDN",
      numericCode: "360",
      phoneCode: "+62",
      continent: "Asia",
      currencyCode: "IDR",
      name: "Indonesia",
      isEU: false,
      languages: [],
    },
    {
      code: "MY",
      iso3: "MYS",
      numericCode: "458",
      phoneCode: "+60",
      continent: "Asia",
      currencyCode: "MYR",
      name: "Malaysia",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "PH",
      iso3: "PHL",
      numericCode: "608",
      phoneCode: "+63",
      continent: "Asia",
      currencyCode: "PHP",
      name: "Filippine",
      isEU: false,
      languages: ["en"],
    },
    {
      code: "VN",
      iso3: "VNM",
      numericCode: "704",
      phoneCode: "+84",
      continent: "Asia",
      currencyCode: "VND",
      name: "Vietnam",
      isEU: false,
      languages: [],
    },
  ];

  // Recupera le lingue disponibili dal database
  const availableLanguages = await prisma.language.findMany({
    select: { iso_code: true },
  });
  const availableIsoCodes = new Set(availableLanguages.map((l) => l.iso_code));

  for (const country of countriesData) {
    // Filtra solo le lingue che esistono nel database
    const validLanguages = country.languages.filter((iso) =>
      availableIsoCodes.has(iso),
    );

    await prisma.country.create({
      data: {
        code: country.code,
        iso3: country.iso3,
        name: country.name,
        numericCode: country.numericCode,
        phoneCode: country.phoneCode,
        continent: country.continent,
        currencyCode: country.currencyCode,
        active: true,
        isEU: country.isEU,
        languages:
          validLanguages.length > 0
            ? {
                connect: validLanguages.map((iso) => ({ iso_code: iso })),
              }
            : undefined,
      },
    });
  }

  console.log(`✅ Creati ${countriesData.length} paesi`);
  console.log(`   - ${countriesData.filter((c) => c.isEU).length} paesi EU`);
  console.log(
    `   - ${countriesData.filter((c) => !c.isEU).length} paesi extra-EU`,
  );
  console.log("🎉 Seeding Country completato!");
}

main()
  .catch((e) => {
    console.error("❌ Errore durante il seeding:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
