// prisma/seeds/currencies.seed.ts

import { prisma } from "@/config/prisma-client";

export async function seedCurrencies() {
  console.log('💰 Seeding currencies...');

  const currenciesData = [
    // === VALUTA BASE ===
    {
      code: 'EUR',
      name: 'Euro',
      namePlural: 'euros',
      symbol: '€',
      symbolNative: '€',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: true,
      exchangeRate: 1.0,
      exchangeRateSource: 'base',
      active: true,
      priority: 1,
      countryCode: 'IT',
    },

    // === VALUTE PRINCIPALI ===
    {
      code: 'USD',
      name: 'US Dollar',
      namePlural: 'US dollars',
      symbol: '$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1.08,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 2,
      countryCode: 'US',
    },
    {
      code: 'GBP',
      name: 'British Pound Sterling',
      namePlural: 'British pounds',
      symbol: '£',
      symbolNative: '£',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 0.86,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 3,
      countryCode: 'GB',
    },
    {
      code: 'CHF',
      name: 'Swiss Franc',
      namePlural: 'Swiss francs',
      symbol: 'CHF',
      symbolNative: 'CHF',
      decimalDigits: 2,
      rounding: 0.05, // Arrotondamento a 5 centesimi
      symbolPosition: 'after',
      decimalSeparator: '.',
      thousandSeparator: "'",
      isBaseCurrency: false,
      exchangeRate: 0.95,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 4,
      countryCode: 'CH',
    },
    {
      code: 'JPY',
      name: 'Japanese Yen',
      namePlural: 'Japanese yen',
      symbol: '¥',
      symbolNative: '¥',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 163.5,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 5,
      countryCode: 'JP',
    },
    {
      code: 'CNY',
      name: 'Chinese Yuan',
      namePlural: 'Chinese yuan',
      symbol: '¥',
      symbolNative: '元',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 7.82,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 6,
      countryCode: 'CN',
    },
    {
      code: 'CAD',
      name: 'Canadian Dollar',
      namePlural: 'Canadian dollars',
      symbol: 'CA$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1.46,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 7,
      countryCode: 'CA',
    },
    {
      code: 'AUD',
      name: 'Australian Dollar',
      namePlural: 'Australian dollars',
      symbol: 'A$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1.63,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 8,
      countryCode: 'AU',
    },

    // === VALUTE EUROPEE NON-EURO ===
    {
      code: 'BGN',
      name: 'Bulgarian Lev',
      namePlural: 'Bulgarian leva',
      symbol: 'лв',
      symbolNative: 'лв',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 1.96, // Fisso a EUR
      exchangeRateSource: 'ECB',
      active: true,
      priority: 20,
      countryCode: 'BG',
    },
    {
      code: 'CZK',
      name: 'Czech Koruna',
      namePlural: 'Czech korunas',
      symbol: 'Kč',
      symbolNative: 'Kč',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 25.1,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 21,
      countryCode: 'CZ',
    },
    {
      code: 'DKK',
      name: 'Danish Krone',
      namePlural: 'Danish kroner',
      symbol: 'kr',
      symbolNative: 'kr',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 7.46, // Fisso a EUR
      exchangeRateSource: 'ECB',
      active: true,
      priority: 22,
      countryCode: 'DK',
    },
    {
      code: 'HUF',
      name: 'Hungarian Forint',
      namePlural: 'Hungarian forints',
      symbol: 'Ft',
      symbolNative: 'Ft',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 396.5,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 23,
      countryCode: 'HU',
    },
    {
      code: 'PLN',
      name: 'Polish Zloty',
      namePlural: 'Polish zlotys',
      symbol: 'zł',
      symbolNative: 'zł',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 4.32,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 24,
      countryCode: 'PL',
    },
    {
      code: 'RON',
      name: 'Romanian Leu',
      namePlural: 'Romanian lei',
      symbol: 'lei',
      symbolNative: 'lei',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 4.97,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 25,
      countryCode: 'RO',
    },
    {
      code: 'SEK',
      name: 'Swedish Krona',
      namePlural: 'Swedish kronor',
      symbol: 'kr',
      symbolNative: 'kr',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 11.48,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 26,
      countryCode: 'SE',
    },
    {
      code: 'NOK',
      name: 'Norwegian Krone',
      namePlural: 'Norwegian kroner',
      symbol: 'kr',
      symbolNative: 'kr',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 11.72,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 27,
      countryCode: 'NO',
    },
    {
      code: 'ISK',
      name: 'Icelandic Króna',
      namePlural: 'Icelandic krónur',
      symbol: 'kr',
      symbolNative: 'kr',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 149.8,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 28,
      countryCode: 'IS',
    },
    {
      code: 'RSD',
      name: 'Serbian Dinar',
      namePlural: 'Serbian dinars',
      symbol: 'дин',
      symbolNative: 'дин',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 117.2,
      exchangeRateSource: 'manual',
      active: true,
      priority: 29,
      countryCode: 'RS',
    },
    {
      code: 'UAH',
      name: 'Ukrainian Hryvnia',
      namePlural: 'Ukrainian hryvnias',
      symbol: '₴',
      symbolNative: '₴',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 44.5,
      exchangeRateSource: 'manual',
      active: true,
      priority: 30,
      countryCode: 'UA',
    },
    {
      code: 'TRY',
      name: 'Turkish Lira',
      namePlural: 'Turkish liras',
      symbol: '₺',
      symbolNative: '₺',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 34.8,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 31,
      countryCode: 'TR',
    },
    {
      code: 'RUB',
      name: 'Russian Ruble',
      namePlural: 'Russian rubles',
      symbol: '₽',
      symbolNative: '₽',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 100.5,
      exchangeRateSource: 'manual',
      active: true,
      priority: 32,
      countryCode: 'RU',
    },

    // === ALTRE VALUTE EUROPEE ===
    {
      code: 'ALL',
      name: 'Albanian Lek',
      namePlural: 'Albanian lekë',
      symbol: 'L',
      symbolNative: 'Lek',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 104.2,
      exchangeRateSource: 'manual',
      active: true,
      priority: 40,
      countryCode: 'AL',
    },
    {
      code: 'BAM',
      name: 'Bosnia-Herzegovina Convertible Mark',
      namePlural: 'Bosnia-Herzegovina convertible marks',
      symbol: 'KM',
      symbolNative: 'KM',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 1.96, // Fisso a EUR
      exchangeRateSource: 'fixed',
      active: true,
      priority: 41,
      countryCode: 'BA',
    },
    {
      code: 'MKD',
      name: 'Macedonian Denar',
      namePlural: 'Macedonian denari',
      symbol: 'ден',
      symbolNative: 'ден',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 61.5,
      exchangeRateSource: 'manual',
      active: true,
      priority: 42,
      countryCode: 'MK',
    },
    {
      code: 'BYN',
      name: 'Belarusian Ruble',
      namePlural: 'Belarusian rubles',
      symbol: 'Br',
      symbolNative: 'Br',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: ' ',
      isBaseCurrency: false,
      exchangeRate: 3.48,
      exchangeRateSource: 'manual',
      active: true,
      priority: 43,
      countryCode: 'BY',
    },
    {
      code: 'MDL',
      name: 'Moldovan Leu',
      namePlural: 'Moldovan lei',
      symbol: 'L',
      symbolNative: 'L',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 19.3,
      exchangeRateSource: 'manual',
      active: true,
      priority: 44,
      countryCode: 'MD',
    },

    // === VALUTE AMERICANE ===
    {
      code: 'MXN',
      name: 'Mexican Peso',
      namePlural: 'Mexican pesos',
      symbol: '$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 18.5,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 50,
      countryCode: 'MX',
    },
    {
      code: 'BRL',
      name: 'Brazilian Real',
      namePlural: 'Brazilian reais',
      symbol: 'R$',
      symbolNative: 'R$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 5.42,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 51,
      countryCode: 'BR',
    },
    {
      code: 'ARS',
      name: 'Argentine Peso',
      namePlural: 'Argentine pesos',
      symbol: '$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 1050.0,
      exchangeRateSource: 'manual',
      active: true,
      priority: 52,
      countryCode: 'AR',
    },

    // === VALUTE ASIATICHE ===
    {
      code: 'KRW',
      name: 'South Korean Won',
      namePlural: 'South Korean won',
      symbol: '₩',
      symbolNative: '₩',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1445.0,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 60,
      countryCode: 'KR',
    },
    {
      code: 'INR',
      name: 'Indian Rupee',
      namePlural: 'Indian rupees',
      symbol: '₹',
      symbolNative: '₹',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 89.8,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 61,
      countryCode: 'IN',
    },
    {
      code: 'SGD',
      name: 'Singapore Dollar',
      namePlural: 'Singapore dollars',
      symbol: 'S$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1.44,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 62,
      countryCode: 'SG',
    },
    {
      code: 'THB',
      name: 'Thai Baht',
      namePlural: 'Thai baht',
      symbol: '฿',
      symbolNative: '฿',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 37.2,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 63,
      countryCode: 'TH',
    },
    {
      code: 'IDR',
      name: 'Indonesian Rupiah',
      namePlural: 'Indonesian rupiahs',
      symbol: 'Rp',
      symbolNative: 'Rp',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'before',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 16850.0,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 64,
      countryCode: 'ID',
    },
    {
      code: 'MYR',
      name: 'Malaysian Ringgit',
      namePlural: 'Malaysian ringgits',
      symbol: 'RM',
      symbolNative: 'RM',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 4.82,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 65,
      countryCode: 'MY',
    },
    {
      code: 'PHP',
      name: 'Philippine Peso',
      namePlural: 'Philippine pesos',
      symbol: '₱',
      symbolNative: '₱',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 60.5,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 66,
      countryCode: 'PH',
    },
    {
      code: 'VND',
      name: 'Vietnamese Dong',
      namePlural: 'Vietnamese dong',
      symbol: '₫',
      symbolNative: '₫',
      decimalDigits: 0, // Nessun decimale
      rounding: 1.0,
      symbolPosition: 'after',
      decimalSeparator: ',',
      thousandSeparator: '.',
      isBaseCurrency: false,
      exchangeRate: 26500.0,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 67,
      countryCode: 'VN',
    },

    // === OCEANIA ===
    {
      code: 'NZD',
      name: 'New Zealand Dollar',
      namePlural: 'New Zealand dollars',
      symbol: 'NZ$',
      symbolNative: '$',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 1.78,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 70,
      countryCode: 'NZ',
    },

    // === AFRICA & MEDIO ORIENTE ===
    {
      code: 'ZAR',
      name: 'South African Rand',
      namePlural: 'South African rand',
      symbol: 'R',
      symbolNative: 'R',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 19.8,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 80,
      countryCode: 'ZA',
    },
    {
      code: 'EGP',
      name: 'Egyptian Pound',
      namePlural: 'Egyptian pounds',
      symbol: '£',
      symbolNative: 'ج.م',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 33.5,
      exchangeRateSource: 'manual',
      active: true,
      priority: 81,
      countryCode: 'EG',
    },
    {
      code: 'SAR',
      name: 'Saudi Riyal',
      namePlural: 'Saudi riyals',
      symbol: '﷼',
      symbolNative: '﷼',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 4.05,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 82,
      countryCode: 'SA',
    },
    {
      code: 'AED',
      name: 'United Arab Emirates Dirham',
      namePlural: 'UAE dirhams',
      symbol: 'د.إ',
      symbolNative: 'د.إ',
      decimalDigits: 2,
      rounding: 0.01,
      symbolPosition: 'before',
      decimalSeparator: '.',
      thousandSeparator: ',',
      isBaseCurrency: false,
      exchangeRate: 3.96,
      exchangeRateSource: 'ECB',
      active: true,
      priority: 83,
      countryCode: 'AE',
    },
  ];

  for (const currency of currenciesData) {
    await prisma.currency.upsert({
      where: { code: currency.code },
      update: {
        ...currency,
        exchangeRateUpdated: new Date(),
      },
      create: {
        ...currency,
        exchangeRateUpdated: new Date(),
      },
    });
  }

  console.log(`✅ Created/updated ${currenciesData.length} currencies`);
}

// Se eseguito direttamente
if (require.main === module) {
  seedCurrencies()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}