// packages/shared/src/validators/index.ts
export * from './base';
export * from './user';
export * from './activity';
export * from './role';
export * from './contact';
export * from './company';
export * from './customer';
export * from './supplier';
export * from './address';
export * from './language';
export * from './country';
export * from './payment';
export * from './tax';
export * from './pricelist';
export * from './opportunity';
export * from './product';
export * from './warehouse';
export * from './attribute';