export type {
  Lead,
  LeadListItem,
  LeadStats,
  CreateLeadInput,
  UpdateLeadInput,
  UpdateLeadStatusInput,
  UpdateLeadScoreInput,
  QualifyLeadInput,
  ConvertLeadInput,
  BulkAssignLeadsInput,
  BulkUpdateLeadStatusInput,
  LeadQueryInput,
  LeadStatsInput,
  LeadIdParam,
} from "@mini-erp/shared/types";